#include "Polinomio.h"




Polinomio& Polinomio::operator+(Polinomio& PolObj)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1-177a48e9:16187dad081:-8000:0000000000000B45 begin
{
}
// section -64--88-56-1-177a48e9:16187dad081:-8000:0000000000000B45 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Polinomio& Polinomio::operator-(Polinomio& PolObj)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1-177a48e9:16187dad081:-8000:0000000000000B48 begin
{
}
// section -64--88-56-1-177a48e9:16187dad081:-8000:0000000000000B48 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Polinomio& Polinomio::operator*(Polinomio& PolObj)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1-177a48e9:16187dad081:-8000:0000000000000B4B begin
{
}
// section -64--88-56-1-177a48e9:16187dad081:-8000:0000000000000B4B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

FcnDTrans& Polinomio::operator/(Polinomio& PolObj)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1-177a48e9:16187dad081:-8000:0000000000000B4F begin
{
}
// section -64--88-56-1-177a48e9:16187dad081:-8000:0000000000000B4F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Polinomio::Polinomio(int intGrado, Rac * RacPt)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1-177a48e9:16187dad081:-8000:0000000000000B56 begin
{
}
// section -64--88-56-1-177a48e9:16187dad081:-8000:0000000000000B56 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

friend ostream& Polinomio::operator<<(ostream& ostreamOut, Polinomio& PolObj)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--494c580d:1618ac1d687:-8000:0000000000000C58 begin
{
}
// section -64--88-56-1--494c580d:1618ac1d687:-8000:0000000000000C58 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
/* lost code following: 
    // section -64--88-56-1-177a48e9:16187dad081:-8000:0000000000000B52 begin
{
}
    // section -64--88-56-1-177a48e9:16187dad081:-8000:0000000000000B52 end
*/