# Project: Project1
# Makefile created by Dev-C++ 4.9.9.2 Built at I. P. N. (México) 2018.05.11.11.04

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = main.o Temario.o Directory_entry.o UT_Directory.o ../../PROGRAMACION_AVANZADA_ENERO-JULIO-2018/PROGRAMACIONAVANZADA/20180507_prep_Lunes/Proyecto_Shell_Operaciones_con_Polinomios/String_Tokenizer.o $(RES)
LINKOBJ  = main.o Temario.o Directory_entry.o UT_Directory.o ../../PROGRAMACION_AVANZADA_ENERO-JULIO-2018/PROGRAMACIONAVANZADA/20180507_prep_Lunes/Proyecto_Shell_Operaciones_con_Polinomios/String_Tokenizer.o $(RES)
LIBS =   
INCS = 
CXXINCS = 
BIN  = ProyectoProgDetallado.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before ProyectoProgDetallado.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "ProyectoProgDetallado.exe" $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

main.i: main.cpp
	$(CPP) -E main.cpp -o main.i $(CXXFLAGS)

Temario.o: Temario.cpp
	$(CPP) -c Temario.cpp -o Temario.o $(CXXFLAGS)

Temario.i: Temario.cpp
	$(CPP) -E Temario.cpp -o Temario.i $(CXXFLAGS)

Directory_entry.o: Directory_entry.cpp
	$(CPP) -c Directory_entry.cpp -o Directory_entry.o $(CXXFLAGS)

Directory_entry.i: Directory_entry.cpp
	$(CPP) -E Directory_entry.cpp -o Directory_entry.i $(CXXFLAGS)

UT_Directory.o: UT_Directory.cpp
	$(CPP) -c UT_Directory.cpp -o UT_Directory.o $(CXXFLAGS)

UT_Directory.i: UT_Directory.cpp
	$(CPP) -E UT_Directory.cpp -o UT_Directory.i $(CXXFLAGS)

../../PROGRAMACION_AVANZADA_ENERO-JULIO-2018/PROGRAMACIONAVANZADA/20180507_prep_Lunes/Proyecto_Shell_Operaciones_con_Polinomios/String_Tokenizer.o: ../../PROGRAMACION_AVANZADA_ENERO-JULIO-2018/PROGRAMACIONAVANZADA/20180507_prep_Lunes/Proyecto_Shell_Operaciones_con_Polinomios/String_Tokenizer.cpp
	$(CPP) -c ../../PROGRAMACION_AVANZADA_ENERO-JULIO-2018/PROGRAMACIONAVANZADA/20180507_prep_Lunes/Proyecto_Shell_Operaciones_con_Polinomios/String_Tokenizer.cpp -o ../../PROGRAMACION_AVANZADA_ENERO-JULIO-2018/PROGRAMACIONAVANZADA/20180507_prep_Lunes/Proyecto_Shell_Operaciones_con_Polinomios/String_Tokenizer.o $(CXXFLAGS)

../../PROGRAMACION_AVANZADA_ENERO-JULIO-2018/PROGRAMACIONAVANZADA/20180507_prep_Lunes/Proyecto_Shell_Operaciones_con_Polinomios/String_Tokenizer.i: ../../PROGRAMACION_AVANZADA_ENERO-JULIO-2018/PROGRAMACIONAVANZADA/20180507_prep_Lunes/Proyecto_Shell_Operaciones_con_Polinomios/String_Tokenizer.cpp
	$(CPP) -E ../../PROGRAMACION_AVANZADA_ENERO-JULIO-2018/PROGRAMACIONAVANZADA/20180507_prep_Lunes/Proyecto_Shell_Operaciones_con_Polinomios/String_Tokenizer.cpp -o ../../PROGRAMACION_AVANZADA_ENERO-JULIO-2018/PROGRAMACIONAVANZADA/20180507_prep_Lunes/Proyecto_Shell_Operaciones_con_Polinomios/String_Tokenizer.i $(CXXFLAGS)
