#include "Rac.h"


    /** 
     *  Clase para representar n\'umeros racionales
     *  @author Lamberto Maza Casas
     *  @version 2018.02.12
     */



int Rac::calc_mcd()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1-57aeb27e:16186f3213c:-8000:0000000000000B37 begin
{
    return 0;
}
// section -64--88-56-1-57aeb27e:16186f3213c:-8000:0000000000000B37 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Rac::set_mcd(int MCD)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1-57aeb27e:16186f3213c:-8000:0000000000000B39 begin
{
    
}
// section -64--88-56-1-57aeb27e:16186f3213c:-8000:0000000000000B39 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Rac& Rac::operator+(Rac& RacObj)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1-57aeb27e:16186f3213c:-8000:0000000000000B48 begin
{
}
// section -64--88-56-1-57aeb27e:16186f3213c:-8000:0000000000000B48 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Rac& Rac::operator-(Rac& RacObj)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1-57aeb27e:16186f3213c:-8000:0000000000000B4C begin
{
}
// section -64--88-56-1-57aeb27e:16186f3213c:-8000:0000000000000B4C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Rac& Rac::operator*(Rac& RacObj)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1-57aeb27e:16186f3213c:-8000:0000000000000B4F begin
{
}
// section -64--88-56-1-57aeb27e:16186f3213c:-8000:0000000000000B4F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Rac& Rac::operator/(Rac& RacObj)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1-57aeb27e:16186f3213c:-8000:0000000000000B52 begin
{
}
// section -64--88-56-1-57aeb27e:16186f3213c:-8000:0000000000000B52 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

friend ostream& Rac::operator<<(ostream& ostreamOut, Rac& RacObj)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--2e9fd5a9:16187923f04:-8000:0000000000000B30 begin
{
}
// section -64--88-56-1--2e9fd5a9:16187923f04:-8000:0000000000000B30 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Rac::Rac(int intNum, int intDen)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--2e9fd5a9:16187923f04:-8000:0000000000000B35 begin
{
}
// section -64--88-56-1--2e9fd5a9:16187923f04:-8000:0000000000000B35 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Rac::Rac()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--2e9fd5a9:16187923f04:-8000:0000000000000B39 begin
{
}
// section -64--88-56-1--2e9fd5a9:16187923f04:-8000:0000000000000B39 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Rac::simplificar()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--2e9fd5a9:16187923f04:-8000:0000000000000B3B begin
{
    
}
// section -64--88-56-1--2e9fd5a9:16187923f04:-8000:0000000000000B3B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
